//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEnergyPrediction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\svm_model\\Results.xls")]
        public string svmresult {
            get {
                return ((string)(this["svmresult"]));
            }
            set {
                this["svmresult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\lm_model\\Results.xls")]
        public string lsrresult {
            get {
                return ((string)(this["lsrresult"]));
            }
            set {
                this["lsrresult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\svm_model\\Summary.pdf")]
        public string svmmodel {
            get {
                return ((string)(this["svmmodel"]));
            }
            set {
                this["svmmodel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\lm_model\\test-analysis.pdf")]
        public string lsrmodel {
            get {
                return ((string)(this["lsrmodel"]));
            }
            set {
                this["lsrmodel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\arima\\sesonal.pdf")]
        public string arimamodel {
            get {
                return ((string)(this["arimamodel"]));
            }
            set {
                this["arimamodel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\SEP\\BE_PROJECT_modified\\ann_model\\model.pdf")]
        public string annmodel {
            get {
                return ((string)(this["annmodel"]));
            }
            set {
                this["annmodel"] = value;
            }
        }
    }
}
